### PR TITLE
Small structural tweaks.

### PR DESCRIPTION
**Pull request by maximelb**
## Description of the change

Small tweaks to enable interactive tasking.
Exposing CoreService in the InteractiveService.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]()

### CODE REVIEW

**Comment by mireaulf** [comment]
Not a huge fan of exposing coreService, why is it needed?

**Comment by maximelb** [comment]
Not a big fan either, but it's needed because we need to switch the core-comms service to using `NewInteractiveService` which returns an `InteractiveService`. But then the `AddCommandHandler` are on the `CoreService`. So we need, from within the service to be able to reach both Core and Interactive, OR we duplicate the handlers, OR we make the Interactive struct "inherit" the Core.

See draft PR https://github.com/refractionPOINT/core-comms-service/pull/21

- Duplicating seems like a lot of wasted code
- Inheriting feels error prone since both structs have quite a few fields.

Suggestions very welcome. :)

**Comment by mireaulf** [comment]
Let's move the `AddCommandHandler` call to `Descriptor` (it makes more sense there)?

**Comment by mireaulf** [comment]
We need to pass the descriptor to both kind of services anyway 😄

**Comment by maximelb** [comment]
Ok so I moved the functionality to Descriptor. But I noticed that that would have two pretty different operating modes for Descriptors, Struct definition and Function call. Seemed weird to populate the whole struct and then call some functions to do what could have been done with just the struct. So I moved the AddHandler to simply be a definition within the struct and moving the validation into a generic IsValid.

In the future we can always move the Descriptor to be more function-based but for now it's better to be just consistent.

This removes the need for access to the CoreService for now.

**Review by mireaulf — APPROVED** [review]

**Pull request merged**
